# Generated by Django 5.2.7 on 2025-11-13 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_tipo_midia_midia'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='servico',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
