# Generated by Django 5.2.6 on 2025-12-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_produto_imagem_servico_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='is_design',
            field=models.BooleanField(default=False),
        ),
    ]
