# Generated by Django 5.2.6 on 2025-12-02 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_servico_is_design'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Midia',
        ),
        migrations.DeleteModel(
            name='Tipo_Midia',
        ),
    ]
